spring:
  profiles:
  active:
  - dev
-----
spring:
  profiels: dev
  application:
    name: microservicecloud-config-hand-dev
------
spring:
  profiles: uat
  application:
    name: microservicecloud-config-han-uat