spring:
  profiles:
  active:
  - dev
---
server:
  port: 8201
spring:
  profiels: dev
  application:
    name: microservicecloud-config-client
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka

---
server:
  port: 8202
spring:
  profiels: uat
  application:
    name: microservicecloud-config-client
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka