spring:
  profiles:
  active:
  - dev
---
server:
  port: 8201
spring:
  profiels: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    sevice-url:
      defautZone: http://localhost:7001/eureka/

---
server:
  port: 8202
spring:
  profiels: uat
  application:
    name: microservicecloud-config-client
eureka:
  client:
    sevice-url:
      defautZone: http://localhost:7001/eureka/