spring:
  profiles:
  active:
  - dev
---
server:
  port: 8203
spring:
  profiels: uat
  application:
    name: microservicecloud-config-client


---
server:
  port: 8204
spring:
  profiels: test
  application:
    name: microservicecloud-config-client
